kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30051
        hostPort: 50051
        protocol: TCP
      - containerPort: 30052
        hostPort: 50052
        protocol: TCP
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30686
        hostPort: 16686
        protocol: TCP
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
