apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat
resources:
  - namespace.yaml
  - ../base
  - server-headless-service.yaml
  - envoy-configmap.yaml
  - envoy-deployment.yaml
  - envoy-service.yaml
patches:
  - path: server-service-nodeport.yaml
  - path: gateway-service-nodeport.yaml
